# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  output_config = debug

else ifeq ($(config),release)
  output_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := output

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

output:
ifneq (,$(output_config))
	@echo "==== Building output ($(output_config)) ===="
	@${MAKE} --no-print-directory -C . -f output.make config=$(output_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f output.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   output"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"